homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  base_url: https://blancqua.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - harmony

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
recorder:
  purge_keep_days: 10

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
# map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr
    name: Weather

# Text to speech
tts:
  - platform: google

# Cloud
cloud:
  google_actions:
    filter:
      include_domains:
        - switch
        - light

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: https://blancqua.duckdns.org:3218

rfxtrx:
  device: /dev/serial/by-id/usb-RFXCOM_RFXtrx433_A1Y0NJGR-if00-port0
light:
  platform: rfxtrx
  automatic_add: False
  devices:
    0b11000002100e0301010f70:
      name: Front Door
    0b11000000df570a01010f40:
      name: Office Lamp
    0b1100000314030f01010f70:
      name: Orientation Lights
    0b11000400727c7e02010f60:
      name: Dressing
switch:
  platform: rfxtrx
  automatic_add: False
  devices:
    0b110007006eac2a01000070:
      name: Home Theatre

vacuum:
  - platform: roomba
    host: 192.168.0.51
    username: !secret roomba_username
    password: !secret roomba_password
    name: Dirty Diana
